version: '3.4'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
        - WEBPACKER_DEV_SERVER_HOST=webpacker
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
  webpacker:
    build: .
    command: /app/bin/webpack-dev-server
    environment:
        - WEBPACKER_DEV_SERVER_HOST=webpacker
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3035:3035"
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
