development:
  adapter: postgresql
  database: concert_development
  pool: 5
  timeout: 1000

test:
  adapter: postgresql
  database: concert_test
  pool: 5
  timeout: 1000

production:
  adapter: postgresql
  database: concert_production
  pool: 5
  timeout: 1000
